version: 2.1

jobs:
  javascript:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: "Build and test"
          command: "npm install && npm run test"

workflows:
  javascript-workflow:
    jobs:
      - javascript
